name: "dbt mermaid"
description: "Draw mermaid flowchart from your dbt project"
branding:
  icon: "bar-chart"
  color: "green"
inputs:
  dbt-version:
    description: "dbt version"
    required: true
    default: "1.7"
  dbt-project:
    description: "the directory of dbt project"
    required: true
    default: "."
  dbt-project-to-compare-with:
    description: "if specified, the differences between two dbt projects are shown"
    required: false
  draw-entire-lineage:
    description: "if false, draw only the differences of two dbt projects and relevant part"
    required: true
    default: true
  save-text-size:
    description: "if true, replace dbt resource name with short hash to save text size"
    required: true
    default: false
outputs:
  filepath:
    description: "The filepath of the mermaid flowchart"
runs:
  using: "node20"
  main: "dist/index.js"
