name: "dbt mermaid"
description: "Draw mermaid flowchart from your dbt project"
inputs:
  dbt-version:
    description: "dbt version"
    required: true
    default: "1.7"
  dbt-project:
    description: "the directory of dbt project"
    required: true
    default: "."
  dbt-project-to-compare-with:
    description: "if specified, the differences between two dbt projects are shown"
    required: false

outputs:
  filepath:
    description: "The filepath of the mermaid flowchart"
runs:
  using: "node20"
  main: "dist/index.js"
