name: "dbt_mermaid"
version: "1.0.0"
config-version: 2

profile: "dbt_mermaid"

model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_mermaid:
    +materialized: view
