dbt_mermaid:
  target: dev
  outputs:
    dev:
      type: postgres

      host: '{{ "postgres" if env_var("CI", "") == "true" else "localhost" }}'
      port: 5432

      dbname: postgres
      schema: main

      user: postgres
      password: password
