on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: dbt-mermaid
        uses: ./
        with:
          dbt-version: 1.7
          dbt-project: project
          save-text-size: true
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.dbt-mermaid.outputs.filepath }}
