on:
  pull_request:
    types: [opened]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.base_ref }}"
          path: base
      - id: dbt-mermaid
        uses: ./
        with:
          dbt-version: 1.7
          dbt-project: project
          dbt-project-to-compare-with: base/project
      - run: cat ${{ steps.dbt-mermaid.outputs.filepath }}
