on:
  pull_request:
    paths: "project/**"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.base_ref }}"
          path: base
      - id: dbt-mermaid
        uses: "./" # kitta65/dbt-mermaid@vX.X.X
        with:
          dbt-version: 1.7.11
          dbt-project: project
          dbt-project-to-compare-with: base/project
          draw-entire-lineage: false
      - name: format comment message
        run: |
          {
            echo '```mermaid'
            cat ${{ steps.dbt-mermaid.outputs.filepath }}
            echo '```'
          } > /tmp/comment.md
      - name: comment on pull request
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: from-actions-comment-pull-request
          filePath: /tmp/comment.md
