on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test

  dbt:
    runs-on: ubuntu-latest
    container: ghcr.io/dbt-labs/postgres:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - run: dbt compile
        working-directory: project
